package com.cardio_generator.outputs;

/**
 * This interface defines the contract for outputting health data generated by different data generators within the
 * cardio_generator system. Implementations of this interface handle the specifics of how data is output, whether it's
 * to the console, a file, or other media.
 *
 * It ensures that all output methods conform to a standardized method call, allowing for flexible outputs
 * without modifying the generators.
 */
public interface OutputStrategy {

    /**
     * Outputs the specified patient data to a designated output medium such as console, file, etc.
     * Implementations determine the exact output format and destination based on the strategy (e.g., writing to files,
     * sending over networks, etc.).
     *
     * @param patientId the unique identifier for the patient whose data is being output. This ID should correspond to
     *                  a valid patient in the health monitoring system.
     * @param timestamp the time at which the data was recorded or generated, expressed in milliseconds since the Unix epoch.
     * @param label a label describing the type of data being output, such as "ECG", "BloodPressure", etc.
     * @param data the actual data to be output, formatted as a string. The format of this data can vary depending on the
     *             implementation and the type of data being handled.
     */
    void output(int patientId, long timestamp, String label, String data);
}

